apiVersion: pullsecrets.ognicki.ooo/v1alpha1
kind: RegistryPullSecret
metadata:
  name: ghcr
spec:
  credentials:
    server: ghcr.io
    username: example-user
    password: example-password
    email: ops@example.com
  namespaces:
    policy: Exclusive
    namespaces:
      - kube-system
    namespaceOverrides:
      - namespace: team-a
        secretName: team-a-ghcr
