apiVersion: v1
kind: Secret
metadata:
  name: ghcr-credentials
  namespace: pull-secrets-operator-system
type: Opaque
stringData:
  server: ghcr.io
  username: example-user
  password: example-password
  email: ops@example.com
