apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "pull-secrets-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pull-secrets-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "pull-secrets-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pull-secrets-operator.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "pull-secrets-operator.serviceAccountName" . }}
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            {{- if .Values.leaderElection.enabled }}
            - --leader-elect
            {{- end }}
            - --metrics-bind-address={{ .Values.metrics.bindAddress }}
            - --health-probe-bind-address={{ .Values.healthProbe.bindAddress }}
          ports:
            - containerPort: 8080
              name: metrics
            - containerPort: 8081
              name: probes
          readinessProbe:
            httpGet:
              path: /readyz
              port: probes
          livenessProbe:
            httpGet:
              path: /healthz
              port: probes
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
